import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";

test("personal upload survives reload and original download, then disappears after deletion", async ({ page, request }) => {
  const email = `documents-${randomUUID()}@example.com`;
  const password = "Documents-browser-123";
  const registered = await request.post("http://127.0.0.1:4015/api/auth/register", { data: { fullName: "Người học tài liệu", email, password, confirmPassword: password, role: "STUDENT" } });
  expect(registered.status()).toBe(201);
  await page.goto("/#/login");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Mật khẩu", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Đăng nhập", exact: true }).click();
  await page.getByRole("link", { name: "Tài liệu của tôi", exact: true }).click();
  await page.getByRole("button", { name: "Thêm tài liệu", exact: true }).click();
  const contents = "Khóa chính xác định duy nhất mỗi bản ghi.";
  await page.locator('input[type="file"]').setInputFiles({ name: "Tài liệu của tôi.txt", mimeType: "text/plain", buffer: Buffer.from(contents) });
  await page.getByRole("button", { name: "Tải tài liệu lên", exact: true }).click();
  await page.getByRole("button", { name: "Xem Tài liệu của tôi.txt", exact: true }).click();
  await page.reload();
  await expect(page.locator("pre")).toHaveText(contents);
  const pending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Tải tệp gốc", exact: true }).click();
  const download = await pending;
  expect(download.suggestedFilename()).toBe("Tài liệu của tôi.txt");
  const stream = await download.createReadStream();
  const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  expect(Buffer.concat(chunks).toString()).toBe(contents);
  await page.getByRole("button", { name: "Xóa tài liệu", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Xóa tài liệu", exact: true }).click();
  await expect(page).toHaveURL(/#\/documents$/);
  await page.reload();
  await expect(page.getByRole("heading", { name: "Không có tài liệu phù hợp" })).toBeVisible();
  const content = "BT /F1 12 Tf 50 750 Td (PDF preview in new tab) Tj ET";
  const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", `<< /Length ${content.length} >>\nstream\n${content}\nendstream`];
  let pdf = "%PDF-1.4\n";
  const offsets = [];
  objects.forEach((object, index) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 6\n0000000000 65535 f \n${offsets.map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  await page.getByRole("button", { name: "Thêm tài liệu", exact: true }).click();
  await page.locator('input[type="file"]').setInputFiles({ name: "Bài học.pdf", mimeType: "application/pdf", buffer: Buffer.from(pdf) });
  await page.getByRole("button", { name: "Tải tài liệu lên", exact: true }).click();
  const downloads = [];
  page.on("download", (item) => downloads.push(item));
  const popupEvent = page.waitForEvent("popup");
  await page.getByRole("row", { name: "Xem tài liệu Bài học.pdf", exact: true }).locator("td").nth(1).click();
  const popup = await popupEvent;
  popup.on("download", (item) => downloads.push(item));
  await expect(popup).toHaveURL(/^blob:/);
  expect(downloads).toHaveLength(0);
  await expect(page).toHaveURL(/#\/documents$/);
  await popup.close();
  const pdfDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Tải xuống Bài học.pdf", exact: true }).click();
  expect((await pdfDownload).suggestedFilename()).toBe("Bài học.pdf");
  await page.getByRole("button", { name: "Xóa Bài học.pdf", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Xóa tài liệu", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Không có tài liệu phù hợp" })).toBeVisible();
});
